query PageQuery {
  ...LayoutQueryFragment
  getPostsList {
    edges {
      node {
        id
        values
        data {
          author {
            ... on AuthorsDocument {
              data {
                ...AuthorsParts
              }
            }
          }
        }
        sys {
          filename
        }
      }
    }
  }
}

query ContentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  getPagesDocument(relativePath: $relativePath) {
    data {
      ...PagesParts
    }
  }
}

query BlogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  getPostsDocument(relativePath: $relativePath) {
    data {
      ...PostsParts
      author {
        ... on AuthorsDocument {
          data {
            name
            avatar
          }
        }
      }
    }
  }
}

query GetPostsPage($after: String) {
  getPostsList(first: 10, after: $after, sort: "date") {
    edges {
      node {
        id
        sys {
          filename
        }
        data {
          title
          excerpt
          date
          _body
          author {
            ... on AuthorsDocument {
              data {
                name
                avatar
              }
            }
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
